---
title: "BME580_porject_EDA"
output:
  pdf_document: default
  html_document: default
date: "2023-02-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(corrplot)
library(gridExtra)
library(tidyverse)
library(patchwork)
library(hms)
```

```{r}
DataRead <- read.csv("stress_all_sensor.csv")
head(DataRead, 10)
# stress level: 0 = no stress; 1 = low stress; 2 = high stress
# EDA (Data from the electrodermal activity sensor expressed as microsiemens (μS))
# HR (extracted from the BVP, The first row is the initial time of the session expressed as unix timestamp in UTC.
# The second row is the sample rate expressed in Hz.)
# TEMP (Celsius (°C))
#ACC (Data from 3-axis accelerometer sensor. The accelerometer is configured to measure acceleration in the range [-2g, 2g]. 
# Therefore the unit in this file is 1/64g.
# Data from x, y, and z axis are respectively in first, second, and third column.)
```


```{r}
# Correlation Matrices

# Select numeric variables & Remove all NA values
numeric_df = DataRead %>% select(c(EDA, HR, TEMP, ACC1, ACC2, ACC3, Stress_level))
numeric_df = numeric_df %>% drop_na()
head(numeric_df, 10)

# 1. For all stress levels
all_stress = numeric_df %>% select(c(EDA, HR, TEMP, ACC1, ACC2, ACC3))
# Construct a correlation matrix using the cor function
corMatrix1 = cor(all_stress)
par(family="Times New Roman")
# par(mfrow=c(1,2))
# Correlation matrix visualization with corrplot
p1 = corrplot(corMatrix1, method='number', order='hclust', 
         title="Correlation Matrix for subject 7A - All Stress Levels",
         mar=c(0,0,1,0)) # Order by angular order of eigenvalues

# 2. For no stress
no_stress <- filter(numeric_df, Stress_level == 0)
no_stress = no_stress %>% select(c(EDA, HR, TEMP, ACC1, ACC2, ACC3))
corMatrix2 = cor(no_stress)
p2 = corrplot(corMatrix2, method='number', order='hclust', 
         title="Correlation Matrix for subject 7A - No Stress",
         mar=c(0,0,1,0))

# 3. For low stress
low_stress <- filter(numeric_df, Stress_level == 1)
low_stress = low_stress %>% select(c(EDA, HR, TEMP, ACC1, ACC2, ACC3))
corMatrix3 = cor(low_stress)
p3 = corrplot(corMatrix3, method='number', order='hclust', 
         title="Correlation Matrix for subject 7A - Low Stress",
         mar=c(0,0,1,0))

# 4. For high stress
high_stress <- filter(numeric_df, Stress_level == 2)
high_stress = high_stress %>% select(c(EDA, HR, TEMP, ACC1, ACC2, ACC3))
corMatrix4 = cor(high_stress)
p4 = corrplot(corMatrix4, method='number', order='hclust', 
         title="Correlation Matrix for subject 7A - High Stress",
         mar=c(0,0,1,0))

#Corplot = (p1 + p2) / (p3 + p4)

#ggsave("correlations.png", plot = Corplot)

```

```{r}
# Overlay the self-report (stress level and duration) to the EDA/temperature/HR to show what the data looks like.

# Use 7A_1587298286 session
Recording <- read.csv("stress_all_sensor_7A_1587298286.csv")
head(Recording, 10)
print(length(Recording$Time))

# Make time elapsed column from Time
Recording$TimeObject <- as.POSIXct(Recording$Time, format="%H:%M:%S")
Reference <- rep("07:11:26", 54675)
Reference <- as.POSIXct(Reference, format="%H:%M:%S")
Recording$TimeElapsed <- Recording$TimeObject - Reference # unit is seconds
#Recording$TimeElapsed <- floor((Recording$TimeObject - Reference)/60) # unit is mins
head(Recording, 30)

# Make a stress level * 100
Recording$Amplified_stress <- Recording$Stress_level * 100
```

```{r}
# Plot one recording, x - time; y - for EDA, HR, TEMP, and Stress_level
#df_eda <- data.frame(TimeElapsed = Recording$TimeElapsed, EDA= Recording$EDA)
#df_hr <- data.frame(TimeElapsed = Recording$TimeElapsed, HR= Recording$HR)
#df_temp <- data.frame(TimeElapsed = Recording$TimeElapsed, TEMP= Recording$TEMP)

EDA_plot = ggplot(Recording, aes(x=TimeElapsed)) + 
  geom_line(aes(y=Stress_level, color="red"))+
  geom_line(aes(y = EDA, color = "blue"))+
  geom_line(aes(y = HR, color = "pink"))+
  geom_line(aes(y = TEMP, color = "orange"))+
  theme(text = element_text(size = 9))+
  scale_fill_discrete(name = "Type", labels = c("Stress_level", "EDA", "HR", "TEMP"))+
  labs(title = "Plots of Three Sensors and Stress Level",
       subtitle = "in One Recording Session for Subject 7A",
       x = "Time elapsed", y = "Sensor data")
EDA_plot
```


```{r}
EDA_plot = ggplot(Recording, aes(x=TimeElapsed)) + 
  geom_line(aes(y = Amplified_stress, color="Stress Level"))+
  geom_line(aes(y = EDA, color = "EDA"))+
  geom_line(aes(y = HR, color = "HR"))+
  geom_line(aes(y = TEMP, color = "Skin temperature"))+
  theme(text = element_text(size = 9))+
  scale_fill_discrete(name = "Type", labels = c("Stress_level", "EDA", "HR", "TEMP"))+
  labs(title = "Plots of Three Sensors and Stress Level",
       subtitle = "in One Recording Session for Subject 7A",
       x = "Time Elapsed (Seconds)", y = "Sensor Data", color = "Legend")
EDA_plot
```

```{r}
Stress_plot = ggplot(Recording, aes(x=TimeElapsed)) + 
  geom_line(aes(y = Stress_level, color="Stress Level"), color = "purple")+
  theme(text = element_text(family="Times New Roman", face="bold", size=14))+
  labs(title = "Stress Level in One Recording Session",
       x = "", y = "Stress", color = "Legend")

EDA_plot = ggplot(Recording, aes(x=TimeElapsed)) + 
  geom_line(aes(y = EDA, color = "EDA"), color = "pink")+
  theme(text = element_text(family="Times New Roman", face="bold", size=14))+
  labs(title = "EDA in One Recording Session",
       x = "", y = "EDA (μS)", color = "Legend")

HR_plot = ggplot(Recording, aes(x=TimeElapsed)) + 
  geom_line(aes(y = HR, color = "HR"), color = "blue")+
  theme(text = element_text(family="Times New Roman", face="bold", size=14))+
  labs(title = "Heart Rate in One Recording Session",
       x = "", y = "HR (bpm)", color = "Legend")

Temp_plot = ggplot(Recording, aes(x=TimeElapsed)) + 
  geom_line(aes(y = TEMP, color = "Skin temperature"), color = "green")+
  theme(text = element_text(family="Times New Roman", face="bold", size=14))+
  labs(title = "Skin Temperature in One Recording Session",
       x = "Time Elapsed (Seconds)", y = "Temp. (°C)")

Plot = Stress_plot / EDA_plot/ HR_plot / Temp_plot
Plot
ggsave("sensors.png", plot = Plot, width = 6, height = 6, dpi=300)

```